const { Pool } = require('pg');
const pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } });

exports.handler = async (event) => {
  const headers = { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': '*' };
    if (event.httpMethod === 'OPTIONS') return { statusCode: 200, headers, body: '' };

      const method = event.httpMethod;
        const params = event.queryStringParameters || {};
          const body = JSON.parse(event.body || '{}');

            try {
                if (method === 'GET') {
                      const date = params.date || new Date().toISOString().split('T')[0];
                            const tasks = await pool.query(
                                    'SELECT * FROM daily_tasks WHERE date=$1 ORDER BY priority DESC, created_at ASC',
                                            [date]
                                                  );
                                                        const stats = await pool.query(
                                                                `SELECT 
                                                                          COUNT(*) as total,
                                                                                    COUNT(*) FILTER (WHERE completed=true) as completed,
                                                                                              COUNT(*) FILTER (WHERE category='content') as content,
                                                                                                        COUNT(*) FILTER (WHERE category='research') as research,
                                                                                                                  COUNT(*) FILTER (WHERE category='posting') as posting,
                                                                                                                            COUNT(*) FILTER (WHERE category='sales') as sales
                                                                                                                                     FROM daily_tasks WHERE date=$1`,
                                                                                                                                             [date]
                                                                                                                                                   );
                                                                                                                                                         
                                                                                                                                                               // Notes - get all
                                                                                                                                                                     const notes = await pool.query('SELECT * FROM notes ORDER BY pinned DESC, updated_at DESC LIMIT 20');
                                                                                                                                                                           // Bookmarks - get all
                                                                                                                                                                                 const bookmarks = await pool.query('SELECT * FROM bookmarks ORDER BY created_at DESC LIMIT 20');
                                                                                                                                                                                       
                                                                                                                                                                                             return { statusCode: 200, headers, body: JSON.stringify({ 
                                                                                                                                                                                                     tasks: tasks.rows, 
                                                                                                                                                                                                             stats: stats.rows[0],
                                                                                                                                                                                                                     notes: notes.rows,
                                                                                                                                                                                                                             bookmarks: bookmarks.rows,
                                                                                                                                                                                                                                     date 
                                                                                                                                                                                                                                           })};
                                                                                                                                                                                                                                               }
                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                   if (method === 'POST') {
                                                                                                                                                                                                                                                         const { action } = body;
                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                     if (action === 'add_task') {
                                                                                                                                                                                                                                                                             const { title, category, priority, date, notes } = body;
                                                                                                                                                                                                                                                                                     const r = await pool.query(
                                                                                                                                                                                                                                                                                               'INSERT INTO daily_tasks (title, category, priority, date, notes) VALUES ($1,$2,$3,$4,$5) RETURNING *',
                                                                                                                                                                                                                                                                                                         [title, category||'general', priority||'medium', date||new Date().toISOString().split('T')[0], notes||'']
                                                                                                                                                                                                                                                                                                                 );
                                                                                                                                                                                                                                                                                                                         return { statusCode: 200, headers, body: JSON.stringify({ success: true, task: r.rows[0] }) };
                                                                                                                                                                                                                                                                                                                               }
                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                     if (action === 'toggle_task') {
                                                                                                                                                                                                                                                                                                                                             const r = await pool.query(
                                                                                                                                                                                                                                                                                                                                                       'UPDATE daily_tasks SET completed=NOT completed WHERE id=$1 RETURNING *',
                                                                                                                                                                                                                                                                                                                                                                 [body.id]
                                                                                                                                                                                                                                                                                                                                                                         );
                                                                                                                                                                                                                                                                                                                                                                                 return { statusCode: 200, headers, body: JSON.stringify({ success: true, task: r.rows[0] }) };
                                                                                                                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                             if (action === 'delete_task') {
                                                                                                                                                                                                                                                                                                                                                                                                     await pool.query('DELETE FROM daily_tasks WHERE id=$1', [body.id]);
                                                                                                                                                                                                                                                                                                                                                                                                             return { statusCode: 200, headers, body: JSON.stringify({ success: true }) };
                                                                                                                                                                                                                                                                                                                                                                                                                   }
                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                         if (action === 'add_note') {
                                                                                                                                                                                                                                                                                                                                                                                                                                 const { title, content, category, tags, pinned } = body;
                                                                                                                                                                                                                                                                                                                                                                                                                                         const r = await pool.query(
                                                                                                                                                                                                                                                                                                                                                                                                                                                   'INSERT INTO notes (title, content, category, tags, pinned) VALUES ($1,$2,$3,$4,$5) RETURNING *',
                                                                                                                                                                                                                                                                                                                                                                                                                                                             [title, content||'', category||'general', tags||[], pinned||false]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                     );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                             return { statusCode: 200, headers, body: JSON.stringify({ success: true, note: r.rows[0] }) };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         if (action === 'update_note') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 const { id, title, content, category, tags, pinned } = body;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         const r = await pool.query(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   'UPDATE notes SET title=$1, content=$2, category=$3, tags=$4, pinned=$5, updated_at=NOW() WHERE id=$6 RETURNING *',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             [title, content, category, tags||[], pinned||false, id]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             return { statusCode: 200, headers, body: JSON.stringify({ success: true, note: r.rows[0] }) };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         if (action === 'delete_note') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 await pool.query('DELETE FROM notes WHERE id=$1', [body.id]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         return { statusCode: 200, headers, body: JSON.stringify({ success: true }) };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     if (action === 'add_bookmark') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             const { title, url, description, category, tags } = body;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     const r = await pool.query(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               'INSERT INTO bookmarks (title, url, description, category, tags) VALUES ($1,$2,$3,$4,$5) RETURNING *',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         [title, url||'', description||'', category||'general', tags||[]]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         return { statusCode: 200, headers, body: JSON.stringify({ success: true, bookmark: r.rows[0] }) };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     if (action === 'delete_bookmark') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             await pool.query('DELETE FROM bookmarks WHERE id=$1', [body.id]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     return { statusCode: 200, headers, body: JSON.stringify({ success: true }) };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 return { statusCode: 400, headers, body: JSON.stringify({ error: 'Unknown action' }) };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         return { statusCode: 405, headers, body: JSON.stringify({ error: 'Method not allowed' }) };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           } catch(e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               return { statusCode: 500, headers, body: JSON.stringify({ error: e.message }) };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 };
